version: "3.8"
services:
  toolfeedback:
    build:
      context: .
      dockerfile: Dockerfile
    image: toolfeedback
    container_name: toolfeedback-server
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/toolfeedback
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 1344
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MONGO_DB_NAME: toolfeedback
      MONGO_PORT: 27017
      MONGO_HOST: mongodb
    ports:
      - 1344:1344
    volumes:
      - .:/app/toolfeedback
      - node_modules:/app/toolfeedback/node_modules
    networks:
      - toolfeedback_network
  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB_NAME=toolfeedback
      - MONGO_PORT=27017
      - MONGO_HOST=127.0.0.1
    networks:
      - toolfeedback_network
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - toolfeedback_network
volumes:
  node_modules:

networks:
  toolfeedback_network:
    driver: bridge
